require: rubocop-rspec

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'

RSpec/MultipleMemoizedHelpers:
  Enabled: false
